/***********************************************************************
*                                                                      *
*               This software is part of the ast package               *
*          Copyright (c) 1992-2015 AT&T Intellectual Property          *
*                      and is licensed under the                       *
*                 Eclipse Public License, Version 1.0                  *
*                    by AT&T Intellectual Property                     *
*                                                                      *
*                A copy of the License is available at                 *
*          http://www.eclipse.org/org/documents/epl-v10.html           *
*         (with md5 checksum b35adb5213ca9657e911e9befb180842)         *
*                                                                      *
*              Information and Software Systems Research               *
*                            AT&T Research                             *
*                           Florham Park NJ                            *
*                                                                      *
*               Glenn Fowler <glenn.s.fowler@gmail.com>                *
*                    David Korn <dgkorn@gmail.com>                     *
*                                                                      *
***********************************************************************/

/* : : generated by proto : : */
                  
/*
 * -lcmd extern function prototypes
 */


#if !defined(__PROTO__)
#include <prototyped.h>
#endif
#if !defined(__LINKAGE__)
#define __LINKAGE__		/* 2004-08-11 transition */
#endif
#include <shcmd.h>

extern __MANGLE__ int	b_basename __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_cat __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_chgrp __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_chmod __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_chown __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_cksum __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_cmp __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_comm __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_cp __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_cut __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_date __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_dirname __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_egrep __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_expr __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_fds __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_fgrep __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_fmt __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_fold __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_getconf __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_grep __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_head __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_iconv __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_id __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_join __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_ln __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_logname __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_ls __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_md5sum __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_mkdir __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_mkfifo __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_mktemp __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_mv __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_od __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_paste __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_pathchk __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_pids __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_readlink __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_realpath __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_rev __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_rm __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_rmdir __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_sha1sum __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_sha256sum __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_sha2sum __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_sha384sum __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_sha512sum __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_stty __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_sum __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_sync __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_tail __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_tee __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_tr __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_tty __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_uname __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_uniq __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_vmstate __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_wc __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_xargs __PROTO__((int, char**, Shbltin_t*));
extern __MANGLE__ int	b_xgrep __PROTO__((int, char**, Shbltin_t*));
