/***********************************************************************
*                                                                      *
*               This software is part of the ast package               *
*          Copyright (c) 1992-2015 AT&T Intellectual Property          *
*                      and is licensed under the                       *
*                 Eclipse Public License, Version 1.0                  *
*                    by AT&T Intellectual Property                     *
*                                                                      *
*                A copy of the License is available at                 *
*          http://www.eclipse.org/org/documents/epl-v10.html           *
*         (with md5 checksum b35adb5213ca9657e911e9befb180842)         *
*                                                                      *
*              Information and Software Systems Research               *
*                            AT&T Research                             *
*                           Florham Park NJ                            *
*                                                                      *
*               Glenn Fowler <glenn.s.fowler@gmail.com>                *
*                    David Korn <dgkorn@gmail.com>                     *
*                                                                      *
***********************************************************************/

/* : : generated by proto : : */
                  
/*
 * -lcmd function list -- define your own CMDLIST()
 */


#if !defined(__PROTO__)
#include <prototyped.h>
#endif
#if !defined(__LINKAGE__)
#define __LINKAGE__		/* 2004-08-11 transition */
#endif
#if _AST_VERSION < 20121001

CMDLIST(basename)
CMDLIST(cat)
CMDLIST(chgrp)
CMDLIST(chmod)
CMDLIST(chown)
CMDLIST(cksum)
CMDLIST(cmp)
CMDLIST(comm)
CMDLIST(cp)
CMDLIST(cut)
CMDLIST(date)
CMDLIST(dirname)
CMDLIST(egrep)
CMDLIST(expr)
CMDLIST(fds)
CMDLIST(fgrep)
CMDLIST(fmt)
CMDLIST(fold)
CMDLIST(getconf)
CMDLIST(grep)
CMDLIST(head)
CMDLIST(iconv)
CMDLIST(id)
CMDLIST(join)
CMDLIST(ln)
CMDLIST(logname)
CMDLIST(ls)
CMDLIST(md5sum)
CMDLIST(mkdir)
CMDLIST(mkfifo)
CMDLIST(mktemp)
CMDLIST(mv)
CMDLIST(od)
CMDLIST(paste)
CMDLIST(pathchk)
CMDLIST(pids)
CMDLIST(readlink)
CMDLIST(realpath)
CMDLIST(rev)
CMDLIST(rm)
CMDLIST(rmdir)
CMDLIST(sha1sum)
CMDLIST(sha256sum)
CMDLIST(sha2sum)
CMDLIST(sha384sum)
CMDLIST(sha512sum)
CMDLIST(stty)
CMDLIST(sum)
CMDLIST(sync)
CMDLIST(tail)
CMDLIST(tee)
CMDLIST(tr)
CMDLIST(tty)
CMDLIST(uname)
CMDLIST(uniq)
CMDLIST(vmstate)
CMDLIST(wc)
CMDLIST(xargs)
CMDLIST(xgrep)

#else

CMDLIST(basename, "/bin")
CMDLIST(cat, "/bin")
CMDLIST(chgrp, "/bin")
CMDLIST(chmod, "/bin")
CMDLIST(chown, "/bin")
CMDLIST(cksum, "/bin")
CMDLIST(cmp, "/bin")
CMDLIST(comm, "/bin")
CMDLIST(cp, "/bin")
CMDLIST(cut, "/bin")
CMDLIST(date, "/bin")
CMDLIST(dirname, "/bin")
CMDLIST(egrep, "/bin")
CMDLIST(expr, "/bin")
CMDLIST(fds, "/usr/bin")
CMDLIST(fgrep, "/bin")
CMDLIST(fmt, "/bin")
CMDLIST(fold, "/bin")
CMDLIST(getconf, "/bin")
CMDLIST(grep, "/bin")
CMDLIST(head, "/bin")
CMDLIST(iconv, "/bin")
CMDLIST(id, "/bin")
CMDLIST(join, "/bin")
CMDLIST(ln, "/bin")
CMDLIST(logname, "/bin")
CMDLIST(ls, "/bin")
CMDLIST(md5sum, "/bin")
CMDLIST(mkdir, "/bin")
CMDLIST(mkfifo, "/bin")
CMDLIST(mktemp, "/bin")
CMDLIST(mv, "/bin")
CMDLIST(od, "/bin")
CMDLIST(paste, "/bin")
CMDLIST(pathchk, "/bin")
CMDLIST(pids, "/usr/bin")
CMDLIST(readlink, "/bin")
CMDLIST(realpath, "/bin")
CMDLIST(rev, "/bin")
CMDLIST(rm, "/bin")
CMDLIST(rmdir, "/bin")
CMDLIST(sha1sum, "/bin")
CMDLIST(sha256sum, "/bin")
CMDLIST(sha2sum, "/usr/bin")
CMDLIST(sha384sum, "/bin")
CMDLIST(sha512sum, "/bin")
CMDLIST(stty, "/bin")
CMDLIST(sum, "/bin")
CMDLIST(sync, "/bin")
CMDLIST(tail, "/bin")
CMDLIST(tee, "/bin")
CMDLIST(tr, "/bin")
CMDLIST(tty, "/bin")
CMDLIST(uname, "/bin")
CMDLIST(uniq, "/bin")
CMDLIST(vmstate, "/usr/bin")
CMDLIST(wc, "/bin")
CMDLIST(xargs, "/bin")
CMDLIST(xgrep, "/usr/bin")

#endif
