
/* : : generated by proto : : */
/***********************************************************************
*                                                                      *
*               This software is part of the ast package               *
*          Copyright (c) 1985-2011 AT&T Intellectual Property          *
*                      and is licensed under the                       *
*                 Eclipse Public License, Version 1.0                  *
*                    by AT&T Intellectual Property                     *
*                                                                      *
*                A copy of the License is available at                 *
*          http://www.eclipse.org/org/documents/epl-v10.html           *
*         (with md5 checksum b35adb5213ca9657e911e9befb180842)         *
*                                                                      *
*              Information and Software Systems Research               *
*                            AT&T Research                             *
*                           Florham Park NJ                            *
*                                                                      *
*               Glenn Fowler <glenn.s.fowler@gmail.com>                *
*                    David Korn <dgkorn@gmail.com>                     *
*                     Phong Vo <phongvo@gmail.com>                     *
*                                                                      *
***********************************************************************/
                  

#ifndef _DT_H
#if !defined(__PROTO__)
#include <prototyped.h>
#endif
#if !defined(__LINKAGE__)
#define __LINKAGE__		/* 2004-08-11 transition */
#endif

#define _DT_H		1

#include <cdt.h>
#include <vmalloc.h>

#if _BLD_cdt && defined(__EXPORT__)
#undef __MANGLE__
#define __MANGLE__ __LINKAGE__		__EXPORT__
#endif

extern __MANGLE__ Dt_t*		dtnew __PROTO__((Vmalloc_t*, Dtdisc_t*, Dtmethod_t*));
extern __MANGLE__ Dt_t*		_dtnew __PROTO__((Vmalloc_t*, Dtdisc_t*, Dtmethod_t*, unsigned long));

#undef __MANGLE__
#define __MANGLE__ __LINKAGE__

#define dtnew(v,d,m)	_dtnew(v,d,m,CDT_VERSION)

#endif
