
/* : : generated by proto : : */
/* : : generated from /home/marvel/Downloads/ksh/src/src/lib/libast/features/dirent by iffe version 2013-11-14 : : */
                  
#ifndef _def_dirent_ast
#if !defined(__PROTO__)
#  if defined(__STDC__) || defined(__cplusplus) || defined(_proto) || defined(c_plusplus)
#    if defined(__cplusplus)
#      define __LINKAGE__	"C"
#    else
#      define __LINKAGE__
#    endif
#    define __STDARG__
#    define __PROTO__(x)	x
#    define __OTORP__(x)
#    define __PARAM__(n,o)	n
#    if !defined(__STDC__) && !defined(__cplusplus)
#      if !defined(c_plusplus)
#      	define const
#      endif
#      define signed
#      define void		int
#      define volatile
#      define __V_		char
#    else
#      define __V_		void
#    endif
#  else
#    define __PROTO__(x)	()
#    define __OTORP__(x)	x
#    define __PARAM__(n,o)	o
#    define __LINKAGE__
#    define __V_		char
#    define const
#    define signed
#    define void		int
#    define volatile
#  endif
#  define __MANGLE__	__LINKAGE__
#  if defined(__cplusplus) || defined(c_plusplus)
#    define __VARARG__	...
#  else
#    define __VARARG__
#  endif
#  if defined(__STDARG__)
#    define __VA_START__(p,a)	va_start(p,a)
#  else
#    define __VA_START__(p,a)	va_start(p)
#  endif
#  if !defined(__INLINE__)
#    if defined(__cplusplus)
#      define __INLINE__	extern __MANGLE__ inline
#    else
#      if defined(_WIN32) && !defined(__GNUC__)
#      	define __INLINE__	__inline
#      endif
#    endif
#  endif
#endif
#if !defined(__LINKAGE__)
#define __LINKAGE__		/* 2004-08-11 transition */
#endif

#define _def_dirent_ast	1
#define _lib_opendir	1	/* opendir() in default lib(s) */
#define _hdr_dirent	1	/* #include <dirent.h> ok */
#define _sys_dir	1	/* #include <sys/dir.h> ok */
#define _nxt_dirent "../include/dirent.h"	/* include path for the native <dirent.h> */
#define _nxt_dirent_str "../include/dirent.h"	/* include string for the native <dirent.h> */
/*
 * <dirent.h> for [fl]stat64 and off64_t
 */

#ifndef _AST_STD_H

#include "../include/dirent.h"	/* the native <dirent.h> */

#else

#ifndef _DIR64_H
#define _DIR64_H

#include <ast_std.h>

#if _typ_off64_t
#undef	off_t
#endif

#include "../include/dirent.h"	/* the native <dirent.h> */

#if _typ_off64_t
#define	off_t		off64_t
#endif

#if _lib_opendir64
#define _ast_opendir	opendir64
#undef	opendir
#define opendir		_ast_opendir
#if _lib_fdopendir64
#undef	fdopendir
#define fdopendir	fdopendir64
#endif
#if _typ_DIR64 && !defined(DIR)
#define DIR		DIR64
#endif
#endif
#if _lib_readdir64 && _typ_struct_dirent64
#ifndef	dirent
#define dirent		dirent64
#endif
#ifndef	readdir
#define readdir		readdir64
#endif
#endif
#if _lib_rewinddir64 && !defined(rewinddir)
#define rewinddir	rewinddir64
#endif
#if _lib_seekdir64 && !defined(seekdir)
#define seekdir		seekdir64
#endif
#if _lib_telldir64 && !defined(telldir)
#define telldir		telldir64
#endif
#if _lib_closedir64 && !defined(closedir)
#define closedir	closedir64
#endif

#endif

#endif
#if _AST_INTERCEPT_IMPLEMENT < 2

#undef	opendir
#define opendir		ast_opendir

#endif

#if _AST_INTERCEPT_IMPLEMENT > 0

#if _BLD_ast && defined(__EXPORT__)
#undef __MANGLE__
#define __MANGLE__ __LINKAGE__		__EXPORT__
#endif

extern __MANGLE__ DIR*	ast_opendir __PROTO__((const char*));

#undef __MANGLE__
#define __MANGLE__ __LINKAGE__

#endif

#endif
